import { Inter } from "next/font/google";
import "./globals.css";
import Sessionprovider from "../components/Sessionprovider";
import Navbar from "../components/Navbar";
import Footbar from "@/components/Footbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Sessionprovider>
            <Navbar />
            {children}
            <Footbar />
          </Sessionprovider>
        </div>
      </body>
    </html>
  );
}
